# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_started', '0010_auto_20170609_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails24',
        ),
        migrations.DeleteModel(
            name='Emails48',
        ),
        migrations.DeleteModel(
            name='Emails7',
        ),
    ]
