# -*- coding: UTF-8 -*-

zone1 = ["Singapore", "Malaysia", "Brunei"]
zone2 = ["American Samoa", "Bangladesh", "Bhutan", "Cambodia", "China", "Fiji", "French Polynesia",
            "Guam", "Hong Kong", "India", "Indonesia", "Kiribati", "North Korea", "South Korea",
            "Northern Mariana Islands", "Macao", "Maldives", "Marshall Islands",
            "Micronesia (Federated States of)", "Mongolia", "Myanmar", "Nauru", "Nepal",
            "New Caledonia", "Pakistan", "Palau", "Papua New Guinea", "Philippines", "Pitcairn",
            "Solomon Islands", "Sri Lanka", "Taiwan", "Thailand", "Timor-Leste", "Tonga", "Tuvalu",
            "Vietnam", "Wallis and Futuna"]
zone3 = ["Afghanistan", "Åland Islands", "Albania", "Algeria", "Andorra", "Angola", "Anguilla",
            "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia",
            "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Barbados", "Belarus", "Belgium", "Belize",
            "Benin", "Bermuda", "Bolivia", "Bonaire, Sint Eustatius and Saba", "Bosnia and Herzegovina",
            "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Bulgaria",
            "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Canada", "Cayman Islands",
            "Central African Republic", "Chad", "Chile", "Christmas Island", "Cocos (Keeling) Islands",
            "Colombia", "Comoros", "Congo", "Congo (the Democratic Republic of the)", "Cook Islands",
            "Costa Rica", "Côte d'Ivoire", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czech Republic",
            "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
            "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands  [Malvinas]",
            "Faroe Islands", "Finland", "France", "French Guiana", "French Southern Territories",
            "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland",
            "Grenada", "Guadeloupe", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana",
            "Haiti", "Heard Island and McDonald Islands", "Holy See", "Honduras", "Hungary", "Iceland",
            "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey",
            "Jordan", "Kazakhstan", "Kenya", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon",
            "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia",
            "Madagascar", "Malawi", "Mali", "Malta", "Martinique", "Mauritania", "Mauritius", "Mayotte",
            "Mexico", "Moldova", "Monaco", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Namibia",
            "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island",
            "Norway", "Oman", "Palestine, State of", "Panama", "Paraguay", "Peru", "Poland", "Portugal",
            "Puerto Rico", "Qatar", "Réunion", "Romania", "Russia", "Rwanda", "Saint Barthélemy",
            "Saint Helena, Ascension and Tristan da Cunha", "Saint Kitts and Nevis", "Saint Lucia",
            "Saint Martin (French part)", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines",
            "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
            "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten (Dutch part)", "Slovakia",
            "Slovenia", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands",
            "South Sudan", "Spain", "Sudan", "Suriname", "Svalbard and Jan Mayen", "Swaziland",
            "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Togo", "Tokelau",
            "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands",
            "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States Minor Outlying Islands",
            "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Virgin Islands (British)",
            "Virgin Islands (U.S.)", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"]
