# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_reminder_recommended_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSkipDelivery',
            fields=[
                ('reminder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reminders.Reminder')),
            ],
            bases=('reminders.reminder',),
        ),
    ]
