# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_reminderskipdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderskipdelivery',
            name='reminder_ptr',
        ),
        migrations.DeleteModel(
            name='ReminderSkipDelivery',
        ),
        migrations.CreateModel(
            name='ReminderSkipDelivery',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reminders.reminder',),
        ),
    ]
