# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0037_emailmanagement'),
        ('reminders', '0008_auto_20170816_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReminderSkipDelivery',
        ),
        migrations.CreateModel(
            name='ReminderSkipDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('from_email', models.CharField(default='Hook Coffee <hola@hookcoffee.com.sg>', max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resumed', models.DateTimeField(blank=True, null=True)),
                ('scheduled', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Order')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Voucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
