# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0010_reminderskipdelivery_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderskipdelivery',
            name='token',
            field=models.CharField(default='dummy', max_length=64),
        ),
    ]
