# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0013_auto_20170925_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersms',
            name='error',
            field=models.CharField(default='', max_length=256),
        ),
    ]
