# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0014_remindersms_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindersms',
            name='error',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
