# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0025_auto_20170705_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeetype',
            name='recommended_brew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffees', to='coffees.BrewMethod'),
        ),
    ]
