# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0026_coffeetype_recommended_brew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeegear',
            name='special',
            field=models.CharField(blank=True, choices=[('set', 'Set'), ('christmas', 'Christmas')], max_length=30, verbose_name='Special for'),
        ),
    ]
