# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-18 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0027_auto_20171016_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeetype',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='coffeetype',
            name='the_order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
