# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0028_auto_20171118_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=2048, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('description', models.CharField(default='A good Course to know more about Coffee', max_length=2048, verbose_name='Description')),
                ('course_status', models.BooleanField(default=True, verbose_name='Available')),
                ('img', models.ImageField(upload_to=b'')),
                ('slug', models.SlugField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('maker', models.CharField(max_length=128, verbose_name='Coffee producer')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('duration', models.CharField(max_length=128, verbose_name='Duration')),
                ('CourseCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.CourseCategory')),
            ],
        ),
    ]
