# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0029_coursecategory_workshops'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='course_cost',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=6, verbose_name='Amount'),
        ),
    ]
