# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0030_workshops_course_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshops',
            old_name='course_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='CourseCategory',
            new_name='course_category',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='course_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='workshops',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Duration'),
        ),
    ]
