# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0032_workshopdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdates',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshopdates', to='coffees.WorkShops'),
        ),
    ]
