# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0035_customer_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('paused', 'paused')], default='active', max_length=32),
        ),
    ]
