# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0036_auto_20170801_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManagement',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('action', django_hstore.fields.DictionaryField(default={})),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailmanagements', to='customers.Customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailmanagements', to='customers.Order')),
            ],
        ),
    ]
