# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0026_coffeetype_recommended_brew'),
        ('customers', '0036_auto_20170801_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeereview',
            name='brew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coffees.BrewMethod'),
        ),
    ]
