# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0037_emailmanagement'),
        ('customers', '0038_coffeereview_hidden'),
    ]

    operations = [
    ]
