# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0039_merge_20170909_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.CharField(choices=[('GR', 'Ground (200g)'), ('WB', 'Wholebeans (200g)'), ('DR', 'Drip bags (x10)'), ('BB', 'Brew bags (x10)'), ('BO', 'Bottled (x6)')], default='GR', max_length=16, verbose_name='Packaging method'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='package',
            field=models.CharField(choices=[('GR', 'Ground (200g)'), ('WB', 'Wholebeans (200g)'), ('DR', 'Drip bags (x10)'), ('BB', 'Brew bags (x10)'), ('BO', 'Bottled (x6)')], default='WB', max_length=16, verbose_name='Packaging method'),
        ),
    ]
