# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0030_workshops_course_cost'),
        ('customers', '0042_auto_20171118_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Shipping date')),
                ('status', models.CharField(choices=[('AC', 'Active'), ('SH', 'Shipped'), ('PA', 'Paused'), ('CA', 'Canceled'), ('ER', 'Failed'), ('DE', 'Declined')], default='AC', max_length=16, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tracking_number', models.CharField(blank=True, max_length=30)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshoporders', to='customers.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshoporders', to='customers.Customer')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Voucher')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.WorkShops')),
            ],
            options={
                'ordering': ['-shipping_date'],
                'default_permissions': ('add', 'change', 'export', 'delete'),
                'abstract': False,
            },
        ),
    ]
