# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-02 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0043_workshoporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoporder',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='workshoporder',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 14, 1, 20, 547037), verbose_name='WorkShop Scheduled Date'),
        ),
    ]
