# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-03 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0044_auto_20180402_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoporder',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 19, 19, 40, 943200), verbose_name='WorkShop Scheduled Date'),
        ),
    ]
