# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-30 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0045_auto_20180403_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoporder',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Number Of People'),
        ),
        migrations.AlterField(
            model_name='workshoporder',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 20, 16, 0, 157698), verbose_name='WorkShop Scheduled Date'),
        ),
    ]
