# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0042_auto_20171118_0023'),
        ('manager', '0004_clusterdf_customercluster_recommendation_reportcard_rightssupport_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadbullOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('consignment_number', models.IntegerField()),
                ('tracking_number', models.IntegerField()),
                ('gear_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redbull', to='customers.GearOrder')),
            ],
        ),
    ]
