# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20171118_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadbullorder',
            name='gear_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadbull', to='customers.GearOrder'),
        ),
    ]
