# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20171119_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadbullorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
